"use client";

import React from "react";
import { AlertTriangle, ArrowLeft, ShieldCheck, CheckSquare } from "lucide-react";
import Link from "next/link";

export default function DisclaimerPage() {
  const lastUpdated = "May 30, 2026";

  return (
    <div className="pt-24 min-h-screen bg-slate-50 text-slate-700">
      {/* Header */}
      <div className="bg-white border-b border-slate-200 py-12 md:py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-emerald-600 hover:text-emerald-700 transition-colors mb-6 group">
            <ArrowLeft className="w-4 h-4 transition-transform group-hover:-translate-x-1" />
            Back to Home
          </Link>
          <div className="flex items-center gap-4 mb-4">
            <div className="w-12 h-12 bg-amber-50 rounded-2xl border border-amber-100 flex items-center justify-center text-amber-600">
              <AlertTriangle className="w-6 h-6" />
            </div>
            <div>
              <span className="text-xs font-bold text-amber-600 uppercase tracking-widest">Regulatory Compliance</span>
              <h1 className="text-3xl md:text-4xl font-extrabold text-slate-900 font-display">RERA Disclaimer</h1>
            </div>
          </div>
          <p className="text-slate-500 text-sm">Last Updated: {lastUpdated} · PropDesk CRM Compliance Guide</p>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-16">
        <div className="bg-white border border-slate-200 rounded-3xl p-6 md:p-12 shadow-sm space-y-8">
          
          <section className="space-y-4">
            <div className="bg-amber-50 border border-amber-200 rounded-2xl p-6 space-y-3">
              <h3 className="font-bold text-amber-950 flex items-center gap-2">
                <AlertTriangle className="w-4 h-4 text-amber-600 flex-shrink-0" />
                Attention Real Estate Agents, Brokers, and Agencies
              </h3>
              <p className="text-sm text-amber-900/80 leading-relaxed">
                The Real Estate (Regulation and Development) Act, 2016 (RERA) mandates strict rules regarding property advertisements, descriptions, and listings. As a software provider, PropDesk provides a private database system for brokers. The broker remains entirely responsible for their own compliance when representing projects and inventory.
              </p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-slate-900 font-display flex items-center gap-2">
              <span className="w-1.5 h-6 bg-emerald-500 rounded-full" />
              1. Platform Nature (SaaS Provider Only)
            </h2>
            <p className="leading-relaxed">
              PropDesk is a Software-as-a-Service (SaaS) CRM platform and is not a real estate agency, developer, RERA-registered broker, or consulting firm. We do not act as intermediaries, represent buyers or developers, or facilitate sales. The software serves strictly as an organizational database tool.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-slate-900 font-display flex items-center gap-2">
              <span className="w-1.5 h-6 bg-emerald-500 rounded-full" />
              2. Accuracy of Broker Listing Databases
            </h2>
            <p className="leading-relaxed">
              All property listing information, project specifications, construction updates, pricing tiers, and RERA numbers in a broker's account are entered and maintained directly by the respective agent or agency. 
            </p>
            <p className="leading-relaxed">
              PropDesk does not pre-vet, verify, or endorse the authenticity, RERA registration status, or legal title of any property listing uploaded by our software users. Any matches generated by our system are based purely on user-inputted keywords and search variables.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-slate-900 font-display flex items-center gap-2">
              <span className="w-1.5 h-6 bg-emerald-500 rounded-full" />
              3. RERA Number Verification Responsibility
            </h2>
            <p className="leading-relaxed">
              Under Indian law, brokers must verify that any project they market has a valid RERA registration number and display it in customer collaterals. When exporting brochures, generating matching lists, or sending WhatsApp PDFs via PropDesk, brokers are strongly advised to ensure the project's correct <strong>RERA Registration Number</strong> is populated accurately in their metadata entries.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-slate-900 font-display flex items-center gap-2">
              <span className="w-1.5 h-6 bg-emerald-500 rounded-full" />
              4. Disclaimer on Localized Unit Calculations
            </h2>
            <p className="leading-relaxed">
              PropDesk contains calculation utilities for land area conversion (such as Gaj, Bigha, Acre, Guntha, Sq. Yard, and Marla). Since regional definitions of local land units may vary in practice across states (e.g., UP, Punjab, Haryana, Rajasthan), these calculations are designed purely as informational estimations. Users must cross-verify precise plot calculations in official registration documents.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-slate-900 font-display flex items-center gap-2">
              <span className="w-1.5 h-6 bg-emerald-500 rounded-full" />
              5. Governing Regulatory Compliance
            </h2>
            <p className="leading-relaxed">
              Brokers using our system must comply with all provisions of state-specific RERA rules (e.g., MahaRERA, HRERA, UP-RERA, etc.). PropDesk Technologies Pvt. Ltd. holds zero liability for any regulatory penalties, consumer disputes, or legal actions resulting from the omission of mandatory disclosures in customer communication sent via the software.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-slate-900 font-display flex items-center gap-2">
              <span className="w-1.5 h-6 bg-emerald-500 rounded-full" />
              6. Need Compliance Assistance?
            </h2>
            <p className="leading-relaxed">
              If you have suggestions on how we can improve our RERA compliance field layout inputs, custom printable watermarks, or have regulatory inquiries, please drop us a message:
            </p>
            <div className="bg-slate-50 border border-slate-200 rounded-2xl p-6 space-y-3 max-w-md">
              <p className="text-sm font-bold text-slate-950">PropDesk Compliance Officer</p>
              <p className="text-sm">📧 Email: <a href="mailto:hardikjain2030@gmail.com" className="text-emerald-650 hover:underline">hardikjain2030@gmail.com</a></p>
              <p className="text-sm">📞 Phone: <a href="tel:+917208850778" className="text-emerald-650 hover:underline">+91 72088 50778</a></p>
            </div>
          </section>

        </div>
      </div>
    </div>
  );
}
